import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getProduct, products } from "@/data/mock-catalog";
import { ProductCard, ProductVisual } from "@/components/site-shell";
import { InquiryButton } from "@/components/catalogue";

export function generateStaticParams() { return products.map((product) => ({ slug: product.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const product = getProduct(slug); return { title: product?.name ?? "Product", description: product?.shortDescription }; }
export default async function ProductPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const product = getProduct(slug); if (!product) notFound(); const related = products.filter((item) => item.id !== product.id && product.occasionIds.some((occasion) => item.occasionIds.includes(occasion))).slice(0, 4); return <main><section className="detail-page"><div className="breadcrumbs">Home / {product.categoryName} / {product.name}</div><div className="detail-visual"><ProductVisual storageId={product.id} src={product.images[0]?.src} tone={product.images[0]?.tone} large alt={product.images[0]?.alt ?? product.name} /></div><div className="detail-copy"><div className="detail-meta"><span>{product.categoryName}</span><span>{product.modelId}</span></div><h1>{product.name}</h1><p className="lead">{product.description}</p><div className="detail-facts"><div className="fact-row"><strong>Materials</strong><span>{product.materials.join(" · ")}</span></div><div className="fact-row"><strong>Finish</strong><span>{product.finish}</span></div><div className="fact-row"><strong>Size</strong><span>{product.dimensions}</span></div><div className="fact-row"><strong>Good for</strong><span>{product.suitableFor.join(" · ")}</span></div></div><div className="detail-actions"><InquiryButton productName={product.name} modelId={product.modelId} /><a className="button button-light" href={`mailto:hello@mosaicresin.example?subject=Enquiry about ${product.name}`}>Share an idea</a></div></div><div className="detail-section"><span className="eyebrow">A note before you inquire</span><h2>Made around the details you bring.</h2><p className="hero-copy">{product.careInstructions} Because resin is handmade, small variations in colour, texture and placement are part of the character. We will confirm what is possible for your specific piece before anything is finalised.</p><div className="tag-list">{product.tags.map((tag) => <span className="tag" key={tag}>{tag}</span>)}</div></div></section>{related.length > 0 && <section className="featured-section"><div className="section-intro"><div><span className="eyebrow">Keep browsing</span><h2>More pieces for this feeling.</h2></div></div><div className="product-grid">{related.map((item) => <ProductCard key={item.id} product={item} />)}</div></section>}</main>; }
